sexp = string | list | abbrev_fn | comp |  quote | backquote | comma | splice | char | symbol | dot
list = lparen sexp? (<whitespace> sexp)* rparen
abbrev_fn = <'['> sexp? (<whitespace> sexp)* <']'>
comp = (name | no_comp) (<':'> name)*
no_comp = <'~'> name
<lparen> = <'('>
<rparen> = <')'>
string = <'"'> any_char* <'"'>
char = <'\\'> name
symbol = name
dot = #'\.'
quote = <'\''> sexp
backquote = <'`'> sexp
comma = <','> sexp
splice = <',@'> sexp
name = #'[a-zA-Z0-9!\-*+_=>]+'
any_char = #'.'
whitespace = #'\s+'
