sexp = string | list | abbrev_fn | comp | type_comp |  quote | backquote | comma | splice | char | symbol | number | dot
number = sign? digit digit* dot? digit?*
sign = '+' | '-'
digit = #'[0-9]'
list = lparen sexp? (<whitespace> sexp)* rparen
abbrev_fn = <'['> sexp? (<whitespace> sexp)* <']'>
comp = (symbol | no_comp) (<':'> symbol | no_comp)*
type_comp = symbol <'|'> symbol
no_comp = <'~'> symbol
<lparen> = <'('>
<rparen> = <')'>
string = <'"'> any_char* <'"'>
char = <'\\'> name
symbol = name
dot = #'\.'
quote = <'\''> sexp
backquote = <'`'> sexp
comma = <','> sexp
splice = <',@'> sexp
name = name_s name_s* digit* name_s*
name_s = #'[a-zA-Z!\-*+_=>\/<\^]+'
any_char = #'.'
whitespace = #'\s+'

